// Your library. Add entries here, drop screenshots in images/.
// Every entry needs: id, group, title, formula, blurb, keywords, imagePrompt, brief.
// `image` and `source` are optional — without an image the card draws a placeholder,
// and both can also be set from inside the app.

// What part of a site a reference covers. An entry may list several.
// Add a term here before using it — check.mjs rejects anything off this list.
const PARTS = [
  'full page', 'navbar', 'hero', 'features', 'gallery', 'testimonials',
  'pricing', 'cta', 'contact', 'footer', 'auth', 'dashboard',
];

const GROUPS = [
  {
    id: 'print-tech-paper',
    name: 'Print-Tech Paper',
    tagline: 'offset artifacts on warm stock',
    what: 'Modern product layouts printed as if they came off a 1970s offset press. Warm uncoated paper ground, halftone dot imagery, ink that sits slightly off-register.',
    means: 'It borrows the credibility of print. Software feels ephemeral; paper feels considered and permanent. Use it when the product is about thinking, writing, or slowness — the texture argues that this thing was made carefully.',
    vocabulary: [
      ['halftone', 'continuous-tone image reproduced as a grid of dots of varying size'],
      ['CMYK misregistration', 'ink plates printed slightly out of alignment, leaving colour fringes'],
      ['paper ground', 'the off-white base colour of the stock, never pure #fff'],
      ['registration marks', 'crosshairs and colour bars printers use to align plates — decorative here'],
      ['dot gain', 'ink spreading on absorbent paper, softening edges'],
      ['overprint', 'one ink laid over another so colours multiply instead of knock out'],
      ['deboss', 'impression pressed into the sheet, read as a soft inner shadow'],
    ],
  },
  {
    id: 'dither-mono',
    name: 'Dither Mono',
    tagline: '1-bit, no greys allowed',
    what: 'Photography crushed to pure black and white, with tone faked entirely by dot patterns. No greyscale, no colour — the image is literally one bit per pixel.',
    means: 'Reads as early computing, zines, and technical honesty. The constraint is visible, so it signals a maker who chose limits on purpose. Strong for dev tools, indie software, and anything anti-corporate.',
    vocabulary: [
      ['1-bit', 'each pixel is on or off; there is no grey'],
      ['error diffusion', 'pushing a pixel\'s rounding error into its neighbours (Floyd–Steinberg)'],
      ['Atkinson dither', 'the Mac-era variant — diffuses less error, so it blows out highlights'],
      ['ordered / Bayer dither', 'fixed threshold matrix; produces a visible regular crosshatch'],
      ['threshold', 'the brightness cutoff that decides black vs white'],
      ['stipple', 'shading built from discrete dots rather than lines'],
      ['duotone', 'the two-colour escape hatch when pure mono is too harsh'],
    ],
  },
  {
    id: 'vast-quiet-cinematic',
    name: 'Vast Quiet Cinematic',
    tagline: 'one small subject, enormous space',
    what: 'Wide, film-grade photography where the subject occupies maybe 5% of the frame and the rest is atmosphere: fog, sky, water, desert. Type sits in the emptiness.',
    means: 'Sells scale and calm simultaneously. The negative space is the message — "we are not shouting at you." Works for infrastructure, finance, health, and premium anything.',
    vocabulary: [
      ['negative space', 'deliberately empty area that gives the subject weight'],
      ['aerial perspective', 'distant objects fading to low contrast through haze'],
      ['long-lens compression', 'telephoto flattening depth so background looms'],
      ['golden hour', 'low warm sun, long shadows, soft falloff'],
      ['letterbox', 'wide crop (2.39:1) that reads as cinema, not photo'],
      ['film grain', 'organic luminance noise; rescues flat digital gradients'],
      ['lifted blacks', 'shadows raised off pure black for a matte, filmic base'],
    ],
  },
  {
    id: 'data-as-texture',
    name: 'Data-as-Texture',
    tagline: 'charts used as ornament',
    what: 'Contour lines, scatter plots, tick marks and monospace callouts deployed as decoration rather than information. The page looks instrumented.',
    means: 'Communicates rigour without a single real number. Say "we measure things" before the visitor reads a word. Default choice for data platforms, quant finance, and observability tools.',
    vocabulary: [
      ['topographic contour', 'nested isolines mapping equal elevation — the signature move'],
      ['isoline', 'any line joining points of equal value'],
      ['sparkline', 'tiny inline chart with no axes'],
      ['tick marks', 'small measurement notches along an edge or rule'],
      ['annotation callout', 'monospace label pinned to a point with a hairline leader'],
      ['scatter field', 'a cloud of small marks read as texture, not data'],
      ['hairline rule', 'sub-pixel-thin line; the whole grammar depends on these staying thin'],
    ],
  },
  {
    id: 'classical-remix',
    name: 'Classical Remix',
    tagline: 'marble meets grid',
    what: 'Greco-Roman statuary, plaster casts and architectural orders dropped into strict modern layouts, usually monochrome and high-contrast.',
    means: 'Borrows permanence and authority. The joke — and it should read as slightly knowing — is applying 2,000-year-old proportion to a two-year-old startup. Good for education, archives, and craft-heavy tools.',
    vocabulary: [
      ['plaster cast', 'matte white copy of a sculpture; reads cleaner than real marble'],
      ['contrapposto', 'the weight-on-one-leg stance that makes a figure look alive'],
      ['entablature', 'the horizontal band a column carries — cornice, frieze, architrave'],
      ['fluted column', 'vertical grooves running the shaft'],
      ['chiaroscuro', 'strong light-to-dark modelling with no mid-tone mush'],
      ['engraving hatch', 'parallel line shading from copperplate printing'],
      ['blueprint overlay', 'measurement lines drawn over the object, as if surveying it'],
    ],
  },
  {
    id: 'glitched-antiquity',
    name: 'Glitched Antiquity',
    tagline: 'archive material, corrupted',
    what: 'Old photographs, engravings or manuscripts run through digital damage — channel splits, pixel sorting, compression artifacts, scanline tears.',
    means: 'The tension is the point: something durable being eaten by something new. Use for AI products, media, archives, anything whose story is "the old thing, transformed."',
    vocabulary: [
      ['datamosh', 'corrupting video keyframes so motion smears across cuts'],
      ['chromatic aberration', 'R/G/B channels offset, leaving colour fringes'],
      ['pixel sort', 'reordering pixels along rows by brightness into streaks'],
      ['scanline', 'horizontal raster lines from CRT display'],
      ['JPEG artifact', 'visible 8×8 blocks and ringing from heavy compression'],
      ['displacement tear', 'a horizontal slab of image shifted sideways'],
      ['VHS bleed', 'colour smearing horizontally past its edge'],
    ],
  },
  {
    id: 'illustrated-storybook',
    name: 'Illustrated Storybook',
    tagline: 'hand-made warmth, flat colour',
    what: 'Painterly or gouache-style illustration with a tight palette, visible texture and no gradients-as-lighting. Rounded, generous, human.',
    means: 'Disarms. Software that touches money, health or children uses this to lower the stakes. The hand-made signal says "a person made this for you," which is exactly what an interface usually fails to say.',
    vocabulary: [
      ['gouache', 'opaque matte watercolour; flat areas with soft edges'],
      ['spot illustration', 'small standalone drawing set into text, no frame'],
      ['limited palette', 'four to six colours total, reused everywhere'],
      ['grain overlay', 'paper noise multiplied over flat fills to kill the vector look'],
      ['vignette', 'edges darkened or faded so the scene sits in a soft pool'],
      ['hand-lettering', 'drawn type, not a font — the one element that must not be neat'],
    ],
  },
  {
    id: 'voxel-dimensional',
    name: 'Voxel & Dimensional',
    tagline: 'the world built from blocks',
    what: 'Isometric 3D scenes assembled from cubes or simple clay-shaded primitives, lit softly and floating on a clean ground.',
    means: 'Digital material rendering a calm subject. It says "this is a constructed system you can see the pieces of" — ideal for anything modular, composable, or explaining its own internals.',
    vocabulary: [
      ['voxel', 'a volumetric pixel — the 3D cube that is the atomic unit'],
      ['isometric projection', 'equal-angle 3D with no perspective convergence'],
      ['orthographic', 'parallel projection; distant objects stay the same size'],
      ['diorama', 'a self-contained miniature scene, cropped away from its surroundings'],
      ['ambient occlusion', 'soft contact shadow where surfaces meet — sells the volume'],
      ['clay shader', 'untextured matte material, colour only, no specular'],
      ['soft studio light', 'large diffuse source, shadows present but never black'],
    ],
  },
  {
    id: 'colour-block-collage',
    name: 'Colour-Block Collage',
    tagline: 'saturated bands, stacked photographs',
    what: 'The page is divided into full-bleed bands of loud flat colour — wine, acid yellow, lime — separated by scalloped or torn edges rather than straight rules. Photography sits on top in overlapping collage clusters, with stickers, seals and sparkles applied over the whole thing.',
    means: 'Volume as a strategy. Where most brands whisper, this shouts and trusts that energy reads as confidence and fun. It signals a place or product you are meant to feel appetite for — travel, food, festivals, events — and it deliberately rejects the restrained neutral palette that every competitor is using.',
    vocabulary: [
      ['colour blocking', 'dividing the layout into large flat fields of saturated colour'],
      ['full-bleed band', 'a section that runs edge to edge carrying its own ground colour'],
      ['scalloped divider', 'a wavy or torn edge between sections instead of a straight rule'],
      ['collage grid', 'photographs of unequal size overlapped and offset rather than aligned'],
      ['sticker element', 'a small graphic — star, sparkle, seal — placed as if stuck on afterwards'],
      ['rosette seal', 'circular stamp-like badge borrowed from packaging and certification'],
      ['hard shadow', 'a solid offset shadow with zero blur, read as a printed second layer'],
      ['complementary clash', 'deliberately jarring colour pairs, e.g. magenta against acid yellow'],
    ],
  },
  {
    id: 'deco-serif-editorial',
    name: 'Deco Serif Editorial',
    tagline: 'display serif on bone, ruled like a contents page',
    what: 'A warm off-white ground carrying an oversized high-contrast display serif — deco or didone, always uppercase, always broken into a short stack of ragged lines. Everything under it is organised by hairline rules and small letterspaced caps, the way a magazine contents page is.',
    means: 'Signals expense through restraint. There is no accent colour, no button that shouts, no card with a shadow — the only thing spending money is the type, which is exactly the argument luxury hospitality, fashion and architecture want to make. Reach for it when the product must feel curated rather than sold.',
    vocabulary: [
      ['didone', 'high-contrast serif with flat hairline serifs and vertical stress'],
      ['stroke contrast', 'the ratio between a letterform\'s thickest and thinnest stroke'],
      ['optical size', 'a cut drawn for large display use — finer hairlines, tighter fit'],
      ['deco ligature', 'the joined or geometricised letter pairs typical of Art Deco display cuts'],
      ['eyebrow', 'small letterspaced caps label sitting above a headline'],
      ['leader rule', 'the rule running from a label across to its value in a contents list'],
      ['ragged stack', 'a headline broken into short uneven lines rather than justified'],
      ['bone stock', 'warm off-white ground, never pure white'],
    ],
  },
];

const ENTRIES = [
  // ── Colour-Block Collage ──────────────────────────────────────────
  {
    id: 'havena',
    group: 'colour-block-collage',
    image: 'images/havena.png',
    source: 'https://dribbble.com/shots/27590961-Havena-Luxury-Hotel-Resort-Website-Landing-Page',
    parts: ['navbar', 'hero'],
    title: 'Havena',
    formula: 'hospitality × colour-block poster',
    blurb: 'Flat wine ground, orange sparkles stuck over the type, and a lavender booking bar dropped straight across the hero.',
    keywords: ['wine-magenta flat ground', 'orange four-point sparkle stickers', 'heavy uppercase headline ending in a period', 'lime buttons with hard offset shadows', 'lavender booking bar overlaying the hero', 'stacked angled colour slabs behind the photo'],
    imagePrompt: '[SUBJECT: a Mediterranean stone villa with a terracotta roof, teal shutters and cream canvas parasols in a cypress garden] photographed in bright midday summer sun under a deep blue sky with crisp white cumulus, deeply saturated colour with warm honey limestone set against dense green cypress and turquoise-teal paintwork, high clarity with strong open shadows, glossy travel-brochure grade with no filmic softness or grain, wide horizontal crop with the building right of centre and foliage filling the left, no haze, no overcast light, no muted or desaturated treatment',
    brief: 'Build the hero for a luxury resort booking site. Ground is a flat wine-magenta (#8B1C5D) inside a near-black plum page frame (#2E0A1F), with faint darker hill silhouettes tinted into the magenta as the only background texture. The headline is a heavy geometric sans, uppercase, white, two centred lines at 64px with 0.92 leading, and it always ends in a full stop; the subhead is two centred lines of 16px warm-white held to 60% width. Nav is 15px white with the active item underlined by a short 3px golden rule. Every button is a hard rectangle carrying a 6px offset shadow in a darker tone with zero blur — the primary is chartreuse (#D6F04B) with black uppercase text and a trailing arrow. Scatter orange (#F0602A) four-point sparkle glyphs at three sizes around the headline, with one of them overlapping a letterform. Float a lavender (#DBC8F2) booking bar across the full content width over the base of the hero: square corners, hairline vertical dividers between CHECK IN, CHECK OUT and GUESTS, each label 11px uppercase in magenta, with golden (#F7C325) circular icon buttons. Below it sits a full-bleed photograph with two thin angled slabs of orange and yellow stacked behind its top edge, offset a few degrees so they read as sheets of paper underneath. Nothing on this page is grey, no shadow is ever blurred, and no corner is rounded except the circular icon buttons.',
  },
  {
    id: 'havena-full',
    group: 'colour-block-collage',
    image: 'images/havena-full.webp',
    source: 'https://dribbble.com/shots/27590961-Havena-Luxury-Hotel-Resort-Website-Landing-Page',
    parts: ['full page'],
    title: 'Havena — full page',
    formula: 'resort marketing site × banded colour collage',
    blurb: 'Eight full-width bands that swap ground colour at every scallop, each one a differently-shaped pile of photographs.',
    keywords: ['alternating wine and marigold bands', 'scalloped wave band edges', 'irregular photo collage per section', 'centred uppercase section headlines', 'rotated rosette seal badges', 'deep indigo footer block'],
    imagePrompt: '[SUBJECT: a set of luxury resort interiors and grounds — arched stone lobbies, a courtyard pool, a terrace table, a lantern-lit spa] photographed in warm golden light with deeply saturated colour, honey limestone and terracotta against turquoise water and deep green planting, rich open shadows and no crushed blacks, glossy travel-brochure grade with high clarity and no grain, each frame composed tightly on its subject with the architecture filling the crop, no haze, no overcast light, no muted or desaturated treatment',
    brief: 'Build a full marketing site for a luxury resort as a vertical stack of eight full-bleed bands that alternate ground colour — wine-magenta (#8B1C5D), marigold (#F5C518), wine, marigold — closing on a deep indigo footer (#3B1B6B), all inside a near-black plum frame (#2E0A1F). Every band boundary is a scalloped wave edge cut as an SVG path, never a straight rule, and no band may share its ground with the one above it. Each band opens with a centred uppercase headline in a heavy geometric sans at 40px ending in a full stop, a two-line centred subhead at 14px, and then a collage: four to seven photographs at deliberately unequal sizes, rounded 10px, overlapping by 20–40px, each captioned in 10px uppercase at its lower-left, and the collage shape must differ band to band — a stepped row here, a staggered mosaic there, a three-card feature elsewhere. Buttons are chartreuse (#D6F04B) or marigold pills with a trailing arrow and a hard 5px offset shadow at zero blur. Scatter orange (#F0602A) four-point sparkles across every band, and pin a rotated circular rosette seal badge into two of them. The testimonial band drops the collage for a single wide photograph with a chartreuse quote card and a script signature laid over it. Footer is a four-column link grid in indigo with circular social buttons. Nothing on this page is grey, no shadow is ever blurred, and every section is centred — there is no left-aligned text anywhere.',
  },

  // ── Illustrated Storybook ─────────────────────────────────────────
  {
    id: 'orely-resorts',
    group: 'illustrated-storybook',
    image: 'images/orely-resorts.webp',
    source: 'https://dribbble.com/shots/26890504-Orely-Resorts-What-Set-Us-Apart-Inner-Page',
    parts: ['navbar', 'hero'],
    title: 'Orely Resorts',
    formula: 'coastal resort × flat vector illustration',
    blurb: 'The whole hero is one drawn scene, and the headline is dropped into the empty sky the illustration deliberately left for it.',
    keywords: ['full-bleed flat vector coastal scene', 'pale sky-blue ground with no gradient shading', 'high-contrast deco serif headline in near-black', 'centred uppercase headline sitting in the sky gap', 'teal, terracotta and blush palette', 'black circular hamburger against the drawing'],
    imagePrompt: '[SUBJECT: a cliffside Mediterranean resort seen from a beach terrace, with palm trees, a parasol, two wooden loungers and a yacht on the water] drawn as flat vector illustration with clean closed shapes and no outlines, colour held to pale sky-blue, deep teal and sage foliage, turquoise water, warm sand, cream stucco with terracotta roofs and blush cushions, shading done only as two or three flat tonal steps per shape with a faint paper grain over the fills, no photographic light and no soft gradients except a single barely-visible sky wash, wide horizontal composition with the scenery pushed to the left and right thirds and a large empty band of sky held open across the middle for type, no perspective distortion, no drop shadows, no outlines',
    brief: 'Build the hero for a boutique resort. The illustration is the page: one full-bleed flat vector scene bleeding to all four edges, with the composition deliberately parted in the centre so a large area of pale sky (#DCEAF2) stays empty. The headline sits in that gap — a high-contrast deco serif, uppercase, near-black (#232B2A), three centred lines at 92px with 0.88 leading and 0.04em tracking, no subhead and no button under it. Nav is a single 56px bar over the illustration with no background plate and no border: a drawn wordmark left, one underlined 13px uppercase link right, and a 56px solid black circle holding a three-bar white menu icon at the far right. At the bottom centre, 11px uppercase letterspaced text reading as a scroll cue, no arrow glyph. Palette is fixed at seven colours — sky #DCEAF2, water #7FC0CE, deep foliage #1E7A6E, terracotta #E8552F, sand #E3D3B8, blush #F6D4D6, ink #232B2A — and nothing on the page may use a colour outside it, including hover states. On scroll, parallax the foreground palm and loungers at 1.15× against the cliff at 0.9× so the scene opens; nothing else moves. No shadows anywhere, no rounded cards, no photographic imagery, and never place a solid panel over the illustration.',
  },

  // ── Deco Serif Editorial ──────────────────────────────────────────
  {
    id: 'orely-what-sets-us-apart',
    group: 'deco-serif-editorial',
    image: 'images/orely-what-sets-us-apart.webp',
    source: 'https://dribbble.com/shots/26890504-Orely-Resorts-What-Set-Us-Apart-Inner-Page',
    parts: ['full page'],
    title: 'Orely Resorts — inner page',
    formula: 'resort hotel × deco serif editorial',
    blurb: 'The illustrated hero hands off to a bone-paper contents page: every section is an eyebrow, a ruled row and a stacked serif headline.',
    keywords: ['warm bone paper ground', 'oversized deco serif uppercase headline in a ragged stack', 'letterspaced caps eyebrow trailed by a short rule', 'numbered 01/ 02/ 03 index rows with hairline leaders and circular line icons', 'unframed photo plates at unequal sizes, no captions or borders', 'pale-to-deep-navy gradient section under white type'],
    imagePrompt: '[SUBJECT: a clifftop resort — an open-air stone bar, a terrace table set for dinner, palms over a pool deck, a whitewashed villa on rock] photographed in soft overcast coastal daylight with no direct sun and no hard shadows, cool restrained grade with muted teal water, bleached stone, pale sky and desaturated green planting, gentle contrast with lifted blacks and no crushed shadow, natural editorial travel photography with fine grain and no HDR clarity, straight-on eye-level framing with the subject filling the crop and the horizon high, no golden-hour warmth, no saturated blues, no vignette, no lens flare',
    brief: 'Build the interior pages of a luxury resort site as a single scrolling document on a warm bone ground (#EDEAE3) with slate ink (#1B2A33). There is no accent colour anywhere — the only colour on the page comes from the photographs and from one full-bleed section whose ground ramps from pale sky (#CFE0EA) to deep navy (#12395C) with all its type reversed to white. Type is a two-role system: a high-contrast deco display serif, uppercase, for every headline, set at 64px with 0.9 leading and broken by hand into three or four short ragged lines that never justify; and the same serif at 20px in sentence case for values and standfirsts. The only sans is an 11px uppercase eyebrow at 0.18em tracking, sitting above each headline and trailed by a 40px hairline rule. Sections are full-width with 160px of vertical padding and a 12-column grid where headlines take columns 1–6 and imagery takes 7–12. The signature component is the index list: numbered rows reading 01/ 02/ 03/ in the serif, each with a 44px circular hairline-outlined line-drawing icon, a 10px caps category label above the value, and a hairline rule spanning the full row width — the rules stagger left and right so no two rows start at the same x. Stats sit as a single row of 56px serif numerals separated by 1px vertical dividers. Photographs are placed as plain rectangles at deliberately unequal sizes, some bleeding off the edge, with no border, no radius, no caption box and no shadow. Nothing on this page is a card, no corner is rounded, no rule is thicker than 1px, and no element may use a colour outside bone, slate, white and the navy gradient.',
  },
];
