// Your library. Add entries here, drop screenshots in images/.
// Every entry needs: id, group, title, formula, blurb, keywords, imagePrompt, brief.
// `image` and `source` are optional — without an image the card draws a placeholder,
// and both can also be set from inside the app.

const GROUPS = [
  {
    id: 'print-tech-paper',
    name: 'Print-Tech Paper',
    tagline: 'offset artifacts on warm stock',
    what: 'Modern product layouts printed as if they came off a 1970s offset press. Warm uncoated paper ground, halftone dot imagery, ink that sits slightly off-register.',
    means: 'It borrows the credibility of print. Software feels ephemeral; paper feels considered and permanent. Use it when the product is about thinking, writing, or slowness — the texture argues that this thing was made carefully.',
    vocabulary: [
      ['halftone', 'continuous-tone image reproduced as a grid of dots of varying size'],
      ['CMYK misregistration', 'ink plates printed slightly out of alignment, leaving colour fringes'],
      ['paper ground', 'the off-white base colour of the stock, never pure #fff'],
      ['registration marks', 'crosshairs and colour bars printers use to align plates — decorative here'],
      ['dot gain', 'ink spreading on absorbent paper, softening edges'],
      ['overprint', 'one ink laid over another so colours multiply instead of knock out'],
      ['deboss', 'impression pressed into the sheet, read as a soft inner shadow'],
    ],
  },
  {
    id: 'dither-mono',
    name: 'Dither Mono',
    tagline: '1-bit, no greys allowed',
    what: 'Photography crushed to pure black and white, with tone faked entirely by dot patterns. No greyscale, no colour — the image is literally one bit per pixel.',
    means: 'Reads as early computing, zines, and technical honesty. The constraint is visible, so it signals a maker who chose limits on purpose. Strong for dev tools, indie software, and anything anti-corporate.',
    vocabulary: [
      ['1-bit', 'each pixel is on or off; there is no grey'],
      ['error diffusion', 'pushing a pixel\'s rounding error into its neighbours (Floyd–Steinberg)'],
      ['Atkinson dither', 'the Mac-era variant — diffuses less error, so it blows out highlights'],
      ['ordered / Bayer dither', 'fixed threshold matrix; produces a visible regular crosshatch'],
      ['threshold', 'the brightness cutoff that decides black vs white'],
      ['stipple', 'shading built from discrete dots rather than lines'],
      ['duotone', 'the two-colour escape hatch when pure mono is too harsh'],
    ],
  },
  {
    id: 'vast-quiet-cinematic',
    name: 'Vast Quiet Cinematic',
    tagline: 'one small subject, enormous space',
    what: 'Wide, film-grade photography where the subject occupies maybe 5% of the frame and the rest is atmosphere: fog, sky, water, desert. Type sits in the emptiness.',
    means: 'Sells scale and calm simultaneously. The negative space is the message — "we are not shouting at you." Works for infrastructure, finance, health, and premium anything.',
    vocabulary: [
      ['negative space', 'deliberately empty area that gives the subject weight'],
      ['aerial perspective', 'distant objects fading to low contrast through haze'],
      ['long-lens compression', 'telephoto flattening depth so background looms'],
      ['golden hour', 'low warm sun, long shadows, soft falloff'],
      ['letterbox', 'wide crop (2.39:1) that reads as cinema, not photo'],
      ['film grain', 'organic luminance noise; rescues flat digital gradients'],
      ['lifted blacks', 'shadows raised off pure black for a matte, filmic base'],
    ],
  },
  {
    id: 'data-as-texture',
    name: 'Data-as-Texture',
    tagline: 'charts used as ornament',
    what: 'Contour lines, scatter plots, tick marks and monospace callouts deployed as decoration rather than information. The page looks instrumented.',
    means: 'Communicates rigour without a single real number. Say "we measure things" before the visitor reads a word. Default choice for data platforms, quant finance, and observability tools.',
    vocabulary: [
      ['topographic contour', 'nested isolines mapping equal elevation — the signature move'],
      ['isoline', 'any line joining points of equal value'],
      ['sparkline', 'tiny inline chart with no axes'],
      ['tick marks', 'small measurement notches along an edge or rule'],
      ['annotation callout', 'monospace label pinned to a point with a hairline leader'],
      ['scatter field', 'a cloud of small marks read as texture, not data'],
      ['hairline rule', 'sub-pixel-thin line; the whole grammar depends on these staying thin'],
    ],
  },
  {
    id: 'classical-remix',
    name: 'Classical Remix',
    tagline: 'marble meets grid',
    what: 'Greco-Roman statuary, plaster casts and architectural orders dropped into strict modern layouts, usually monochrome and high-contrast.',
    means: 'Borrows permanence and authority. The joke — and it should read as slightly knowing — is applying 2,000-year-old proportion to a two-year-old startup. Good for education, archives, and craft-heavy tools.',
    vocabulary: [
      ['plaster cast', 'matte white copy of a sculpture; reads cleaner than real marble'],
      ['contrapposto', 'the weight-on-one-leg stance that makes a figure look alive'],
      ['entablature', 'the horizontal band a column carries — cornice, frieze, architrave'],
      ['fluted column', 'vertical grooves running the shaft'],
      ['chiaroscuro', 'strong light-to-dark modelling with no mid-tone mush'],
      ['engraving hatch', 'parallel line shading from copperplate printing'],
      ['blueprint overlay', 'measurement lines drawn over the object, as if surveying it'],
    ],
  },
  {
    id: 'glitched-antiquity',
    name: 'Glitched Antiquity',
    tagline: 'archive material, corrupted',
    what: 'Old photographs, engravings or manuscripts run through digital damage — channel splits, pixel sorting, compression artifacts, scanline tears.',
    means: 'The tension is the point: something durable being eaten by something new. Use for AI products, media, archives, anything whose story is "the old thing, transformed."',
    vocabulary: [
      ['datamosh', 'corrupting video keyframes so motion smears across cuts'],
      ['chromatic aberration', 'R/G/B channels offset, leaving colour fringes'],
      ['pixel sort', 'reordering pixels along rows by brightness into streaks'],
      ['scanline', 'horizontal raster lines from CRT display'],
      ['JPEG artifact', 'visible 8×8 blocks and ringing from heavy compression'],
      ['displacement tear', 'a horizontal slab of image shifted sideways'],
      ['VHS bleed', 'colour smearing horizontally past its edge'],
    ],
  },
  {
    id: 'illustrated-storybook',
    name: 'Illustrated Storybook',
    tagline: 'hand-made warmth, flat colour',
    what: 'Painterly or gouache-style illustration with a tight palette, visible texture and no gradients-as-lighting. Rounded, generous, human.',
    means: 'Disarms. Software that touches money, health or children uses this to lower the stakes. The hand-made signal says "a person made this for you," which is exactly what an interface usually fails to say.',
    vocabulary: [
      ['gouache', 'opaque matte watercolour; flat areas with soft edges'],
      ['spot illustration', 'small standalone drawing set into text, no frame'],
      ['limited palette', 'four to six colours total, reused everywhere'],
      ['grain overlay', 'paper noise multiplied over flat fills to kill the vector look'],
      ['vignette', 'edges darkened or faded so the scene sits in a soft pool'],
      ['hand-lettering', 'drawn type, not a font — the one element that must not be neat'],
    ],
  },
  {
    id: 'voxel-dimensional',
    name: 'Voxel & Dimensional',
    tagline: 'the world built from blocks',
    what: 'Isometric 3D scenes assembled from cubes or simple clay-shaded primitives, lit softly and floating on a clean ground.',
    means: 'Digital material rendering a calm subject. It says "this is a constructed system you can see the pieces of" — ideal for anything modular, composable, or explaining its own internals.',
    vocabulary: [
      ['voxel', 'a volumetric pixel — the 3D cube that is the atomic unit'],
      ['isometric projection', 'equal-angle 3D with no perspective convergence'],
      ['orthographic', 'parallel projection; distant objects stay the same size'],
      ['diorama', 'a self-contained miniature scene, cropped away from its surroundings'],
      ['ambient occlusion', 'soft contact shadow where surfaces meet — sells the volume'],
      ['clay shader', 'untextured matte material, colour only, no specular'],
      ['soft studio light', 'large diffuse source, shadows present but never black'],
    ],
  },
  {
    id: 'colour-block-collage',
    name: 'Colour-Block Collage',
    tagline: 'saturated bands, stacked photographs',
    what: 'The page is divided into full-bleed bands of loud flat colour — wine, acid yellow, lime — separated by scalloped or torn edges rather than straight rules. Photography sits on top in overlapping collage clusters, with stickers, seals and sparkles applied over the whole thing.',
    means: 'Volume as a strategy. Where most brands whisper, this shouts and trusts that energy reads as confidence and fun. It signals a place or product you are meant to feel appetite for — travel, food, festivals, events — and it deliberately rejects the restrained neutral palette that every competitor is using.',
    vocabulary: [
      ['colour blocking', 'dividing the layout into large flat fields of saturated colour'],
      ['full-bleed band', 'a section that runs edge to edge carrying its own ground colour'],
      ['scalloped divider', 'a wavy or torn edge between sections instead of a straight rule'],
      ['collage grid', 'photographs of unequal size overlapped and offset rather than aligned'],
      ['sticker element', 'a small graphic — star, sparkle, seal — placed as if stuck on afterwards'],
      ['rosette seal', 'circular stamp-like badge borrowed from packaging and certification'],
      ['hard shadow', 'a solid offset shadow with zero blur, read as a printed second layer'],
      ['complementary clash', 'deliberately jarring colour pairs, e.g. magenta against acid yellow'],
    ],
  },
];

const ENTRIES = [
  // ── Colour-Block Collage ──────────────────────────────────────────
  {
    id: 'havena',
    group: 'colour-block-collage',
    title: 'Havena',
    formula: 'hospitality × sticker collage',
    blurb: 'Every section changes ground colour and every photo is pasted on at a different size — the page never once sits still.',
    keywords: ['wine and acid-yellow colour blocking', 'scalloped wave section dividers', 'overlapping photo collage clusters', 'heavy condensed uppercase headlines', 'four-point sparkle stickers', 'lime pill buttons with arrows'],
    imagePrompt: '[SUBJECT: a Mediterranean villa courtyard with a turquoise pool, cypress trees and cream canvas parasols] photographed in high Mediterranean sun, deeply saturated colour with warm terracotta and ochre stone set against turquoise water and dense green foliage, strong contrast with rich warm shadows, vintage travel-poster colour grade pushing magenta into the shadow tones, tight crop with the architecture filling the frame and no empty sky, no haze, no pastel wash, no muted or desaturated treatment',
    brief: 'Build a landing page for a luxury resort. The page is a stack of full-bleed bands that alternate ground colour — wine (#6E1338), acid yellow (#F3C61B), wine, lime (#D2E75E) — with a deep plum footer (#3A1040); every band change is separated by a scalloped wave edge cut as an SVG path, never a straight rule. Headlines are a heavy condensed uppercase sans at 48px with tight leading, always ending in a full stop, and always centred; body is a small warm-cream sans at 15px. The logo is an italic script wordmark, the one soft shape on the page. Each section is a collage: four to seven photographs at deliberately unequal sizes, rounded 12px, overlapping by 20–40px and rotated no more than 2 degrees, each with a small uppercase caption pinned to its lower-left. Scatter four-point sparkle glyphs and one circular rosette seal badge over the layout as stickers, including over photo edges. Buttons are lime or yellow pills with a trailing arrow and a hard 4px offset shadow in a darker tone — zero blur on every shadow on the page. Overlay the hero with a floating booking bar: rounded, wine-on-wine, with hairline field dividers. Nothing on this page may be neutral grey, and no section may share its ground colour with the one above it.',
  },
];
